"""
RD++ (Revisiting Reverse Distillation) Training Script
========================================================

Trains an RD++ anomaly-detection model (CVPR 2023, Tran Dinh Tien et al.)
on a folder of OK images with zero user interaction.

How RD++ works:
  1. A pretrained WideResNet-50-2 encoder extracts multi-scale features
     from layer1, layer2, layer3 (frozen — never updated).
  2. A Bottleneck Network (OCE-BN) aggregates and compresses the multi-scale
     features into a compact one-class embedding.
  3. A reverse decoder (mirror of the encoder with transposed convolutions)
     reconstructs the encoder features from the BN output.
  4. A Multi-Projection Layer projects encoder features for self-supervised
     optimal-transport (SSOT) regularisation.
  5. Pseudo-anomalies are generated by injecting structured noise
     (approximating simplex noise) into training images.

The core idea: the decoder learns to reconstruct normal features. At inference,
anomalous regions produce features the decoder cannot reconstruct, yielding
high cosine-distance anomaly scores.

Architecture (WideResNet-50-2 backbone):
  - Encoder:     frozen WRN50-2, returns [layer1(256ch), layer2(512ch), layer3(1024ch)]
  - BN layer:    aggregates 3 scales → [2048, 8, 8] bottleneck
  - Decoder:     reverse WRN50-2 with ConvTranspose2d → [256ch, 512ch, 1024ch]
  - Projection:  3× ProjLayer (conv bottleneck per scale)

Training losses:
  - L_distill:  cosine similarity between encoder and decoder features
  - L_proj:     (SSOT + 0.01×reconstruct + 0.1×contrastive) / 1.11
  - L_total:    L_distill + weight_proj × L_proj

Optimiser setup:
  - Projection:  Adam lr=1e-3, betas=(0.5, 0.999)
  - Distillation (decoder + BN): Adam lr=5e-3, betas=(0.5, 0.999)
  - Gradient accumulation: 2 steps (effective batch = 2 × batch_size)

Checkpoint format (.pth):
  { decoder_state_dict, bn_state_dict, proj_state_dict, config }
"""

import logging
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from scipy.ndimage import gaussian_filter as scipy_gaussian_filter
from torch.utils.data import DataLoader, Dataset
from torchvision import models, transforms

try:
    import geomloss

    HAS_GEOMLOSS = True
except ImportError:
    HAS_GEOMLOSS = False

logger = logging.getLogger(__name__)

# Common image file extensions (consistent with dataset_splitter)
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif"}

# ImageNet normalisation constants
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

# Minimum number of OK training images.
# RD++ uses knowledge distillation and works with fewer images
# than discriminative approaches like SimpleNet.
MIN_TRAIN_IMAGES = 10


# ======================================================================== #
#  Encoder — frozen pretrained WideResNet-50-2                              #
# ======================================================================== #


class Encoder(nn.Module):
    """Pretrained WideResNet-50-2 that returns multi-scale features.

    Extracts features from layer1, layer2, layer3:
      - layer1: [B, 256, H/4,  W/4]  = [B, 256, 64, 64] for 256×256 input
      - layer2: [B, 512, H/8,  W/8]  = [B, 512, 32, 32]
      - layer3: [B, 1024, H/16, W/16] = [B, 1024, 16, 16]

    All parameters are frozen — the encoder is never updated.
    """

    def __init__(self) -> None:
        super().__init__()
        backbone = models.wide_resnet50_2(weights="IMAGENET1K_V1")

        self.conv1 = backbone.conv1
        self.bn1 = backbone.bn1
        self.relu = backbone.relu
        self.maxpool = backbone.maxpool
        self.layer1 = backbone.layer1
        self.layer2 = backbone.layer2
        self.layer3 = backbone.layer3

        # Freeze every parameter
        for p in self.parameters():
            p.requires_grad = False

    @torch.no_grad()
    def forward(self, x: torch.Tensor) -> list[torch.Tensor]:
        x = self.maxpool(self.relu(self.bn1(self.conv1(x))))
        feat_a = self.layer1(x)
        feat_b = self.layer2(feat_a)
        feat_c = self.layer3(feat_b)
        return [feat_a, feat_b, feat_c]


# ======================================================================== #
#  Decoder — reverse ResNet with transposed convolutions                    #
# ======================================================================== #


def _conv3x3(in_planes: int, out_planes: int, stride: int = 1) -> nn.Conv2d:
    return nn.Conv2d(
        in_planes,
        out_planes,
        kernel_size=3,
        stride=stride,
        padding=1,
        bias=False,
    )


def _conv1x1(in_planes: int, out_planes: int, stride: int = 1) -> nn.Conv2d:
    return nn.Conv2d(in_planes, out_planes, kernel_size=1, stride=stride, bias=False)


def _deconv2x2(in_planes: int, out_planes: int, stride: int = 1) -> nn.ConvTranspose2d:
    return nn.ConvTranspose2d(
        in_planes,
        out_planes,
        kernel_size=2,
        stride=stride,
        bias=False,
    )


class DecoderBottleneck(nn.Module):
    """Bottleneck block with ConvTranspose2d upsampling (stride=2)."""

    expansion = 4

    def __init__(
        self,
        inplanes: int,
        planes: int,
        stride: int = 1,
        upsample: nn.Module | None = None,
        base_width: int = 64,
    ) -> None:
        super().__init__()
        width = int(planes * (base_width / 64.0))

        self.conv1 = _conv1x1(inplanes, width)
        self.bn1 = nn.BatchNorm2d(width)

        if stride == 2:
            self.conv2 = _deconv2x2(width, width, stride)
        else:
            self.conv2 = _conv3x3(width, width, stride)

        self.bn2 = nn.BatchNorm2d(width)
        self.conv3 = _conv1x1(width, planes * self.expansion)
        self.bn3 = nn.BatchNorm2d(planes * self.expansion)
        self.relu = nn.ReLU(inplace=True)
        self.upsample = upsample

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        identity = x
        out = self.relu(self.bn1(self.conv1(x)))
        out = self.relu(self.bn2(self.conv2(out)))
        out = self.bn3(self.conv3(out))
        if self.upsample is not None:
            identity = self.upsample(x)
        out += identity
        return self.relu(out)


class Decoder(nn.Module):
    """Reverse WideResNet-50-2 decoder.

    Mirrors the encoder in reverse order using transposed convolutions
    for spatial upsampling:
      Input:  [B, 2048, 8, 8]   (from Bottleneck Network)
      layer1: 2048 → 1024,  8 → 16
      layer2: 1024 → 512,  16 → 32
      layer3:  512 → 256,  32 → 64

    Returns features in order **matching the encoder**:
      [feat_256ch_64×64, feat_512ch_32×32, feat_1024ch_16×16]
    """

    def __init__(self, layers: tuple = (3, 4, 6), width_per_group: int = 128) -> None:
        super().__init__()
        self.inplanes = 2048
        self.base_width = width_per_group

        self.layer1 = self._make_layer(256, layers[0], stride=2)
        self.layer2 = self._make_layer(128, layers[1], stride=2)
        self.layer3 = self._make_layer(64, layers[2], stride=2)

        self._init_weights()

    # ---- helpers ----

    def _make_layer(self, planes: int, blocks: int, stride: int = 1) -> nn.Sequential:
        upsample = None
        if stride != 1 or self.inplanes != planes * DecoderBottleneck.expansion:
            upsample = nn.Sequential(
                _deconv2x2(self.inplanes, planes * DecoderBottleneck.expansion, stride),
                nn.BatchNorm2d(planes * DecoderBottleneck.expansion),
            )

        block_list: list[nn.Module] = [
            DecoderBottleneck(
                self.inplanes,
                planes,
                stride,
                upsample,
                base_width=self.base_width,
            )
        ]
        self.inplanes = planes * DecoderBottleneck.expansion
        for _ in range(1, blocks):
            block_list.append(
                DecoderBottleneck(
                    self.inplanes,
                    planes,
                    base_width=self.base_width,
                )
            )
        return nn.Sequential(*block_list)

    def _init_weights(self) -> None:
        for m in self.modules():
            if isinstance(m, (nn.Conv2d, nn.ConvTranspose2d)):
                nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

    # ---- forward ----

    def forward(self, x: torch.Tensor) -> list[torch.Tensor]:
        feat_a = self.layer1(x)  # [B, 1024, 16, 16]
        feat_b = self.layer2(feat_a)  # [B, 512,  32, 32]
        feat_c = self.layer3(feat_b)  # [B, 256,  64, 64]
        return [feat_c, feat_b, feat_a]  # [256, 512, 1024] matches encoder


# ======================================================================== #
#  Bottleneck Network (OCE — One-Class Embedding)                           #
# ======================================================================== #


class BNBottleneck(nn.Module):
    """Standard ResNet Bottleneck for the aggregation network."""

    expansion = 4

    def __init__(
        self,
        inplanes: int,
        planes: int,
        stride: int = 1,
        downsample: nn.Module | None = None,
        base_width: int = 64,
    ) -> None:
        super().__init__()
        width = int(planes * (base_width / 64.0))
        self.conv1 = _conv1x1(inplanes, width)
        self.bn1 = nn.BatchNorm2d(width)
        self.conv2 = _conv3x3(width, width, stride)
        self.bn2 = nn.BatchNorm2d(width)
        self.conv3 = _conv1x1(width, planes * self.expansion)
        self.bn3 = nn.BatchNorm2d(planes * self.expansion)
        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        identity = x
        out = self.relu(self.bn1(self.conv1(x)))
        out = self.relu(self.bn2(self.conv2(out)))
        out = self.bn3(self.conv3(out))
        if self.downsample is not None:
            identity = self.downsample(x)
        out += identity
        return self.relu(out)


class BottleneckNetwork(nn.Module):
    """Bottleneck Network for multi-scale feature aggregation.

    Processes 3 encoder features at different scales:
      feature_a [B, 256, 64, 64]  → downsample ×4 → [B, 1024, 16, 16]
      feature_b [B, 512, 32, 32]  → downsample ×2 → [B, 1024, 16, 16]
      feature_c [B, 1024, 16, 16] → unchanged

    Concatenated → [B, 3072, 16, 16]
    BN blocks (stride=2) → [B, 2048, 8, 8]
    """

    def __init__(self, width_per_group: int = 128) -> None:
        super().__init__()
        exp = 4  # Bottleneck expansion

        # Downsample feature_a: 256 → 512 (stride 2) → 1024 (stride 2)
        self.conv1 = _conv3x3(64 * exp, 128 * exp, stride=2)
        self.bn1 = nn.BatchNorm2d(128 * exp)
        self.conv2 = _conv3x3(128 * exp, 256 * exp, stride=2)
        self.bn2 = nn.BatchNorm2d(256 * exp)

        # Downsample feature_b: 512 → 1024 (stride 2)
        self.conv3 = _conv3x3(128 * exp, 256 * exp, stride=2)
        self.bn3 = nn.BatchNorm2d(256 * exp)

        self.relu = nn.ReLU(inplace=True)

        # Main bottleneck: 3072(=1024×3) → 2048, stride=2 → [B, 2048, 8, 8]
        in_channels = 256 * exp * 3  # 3072
        out_channels = 512 * exp  # 2048
        self.base_width = width_per_group

        downsample = nn.Sequential(
            _conv1x1(in_channels, out_channels, stride=2),
            nn.BatchNorm2d(out_channels),
        )
        blocks: list[nn.Module] = [
            BNBottleneck(
                in_channels,
                512,
                stride=2,
                downsample=downsample,
                base_width=width_per_group,
            ),
        ]
        for _ in range(2):  # 2 more blocks at 2048→2048
            blocks.append(
                BNBottleneck(out_channels, 512, base_width=width_per_group),
            )
        self.bn_layer = nn.Sequential(*blocks)

        self._init_weights()

    def _init_weights(self) -> None:
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

    def forward(self, features: list[torch.Tensor]) -> torch.Tensor:
        feat_a, feat_b, feat_c = features

        l1 = self.relu(self.bn2(self.conv2(self.relu(self.bn1(self.conv1(feat_a))))))
        l2 = self.relu(self.bn3(self.conv3(feat_b)))

        feature = torch.cat([l1, l2, feat_c], dim=1)
        return self.bn_layer(feature).contiguous()


# ======================================================================== #
#  Multi-Projection Layer                                                   #
# ======================================================================== #


class ProjLayer(nn.Module):
    """Single-scale projection head (4-layer conv bottleneck)."""

    def __init__(self, in_c: int, out_c: int) -> None:
        super().__init__()
        self.proj = nn.Sequential(
            nn.Conv2d(in_c, in_c // 2, 3, 1, 1),
            nn.InstanceNorm2d(in_c // 2),
            nn.LeakyReLU(inplace=True),
            nn.Conv2d(in_c // 2, in_c // 4, 3, 1, 1),
            nn.InstanceNorm2d(in_c // 4),
            nn.LeakyReLU(inplace=True),
            nn.Conv2d(in_c // 4, in_c // 2, 3, 1, 1),
            nn.InstanceNorm2d(in_c // 2),
            nn.LeakyReLU(inplace=True),
            nn.Conv2d(in_c // 2, out_c, 3, 1, 1),
            nn.InstanceNorm2d(out_c),
            nn.LeakyReLU(inplace=True),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.proj(x)


class MultiProjectionLayer(nn.Module):
    """Multi-scale projection for self-supervised optimal transport.

    One ProjLayer per encoder scale:
      layer1 (256ch), layer2 (512ch), layer3 (1024ch).
    """

    def __init__(self, base: int = 64) -> None:
        super().__init__()
        self.proj_a = ProjLayer(base * 4, base * 4)
        self.proj_b = ProjLayer(base * 8, base * 8)
        self.proj_c = ProjLayer(base * 16, base * 16)

    def forward(
        self,
        features: list[torch.Tensor],
        features_noise: list[torch.Tensor] | None = None,
    ) -> list[torch.Tensor] | tuple[list[torch.Tensor], list[torch.Tensor]]:
        if features_noise is not None:
            return (
                [
                    self.proj_a(features_noise[0]),
                    self.proj_b(features_noise[1]),
                    self.proj_c(features_noise[2]),
                ],
                [
                    self.proj_a(features[0]),
                    self.proj_b(features[1]),
                    self.proj_c(features[2]),
                ],
            )
        return [
            self.proj_a(features[0]),
            self.proj_b(features[1]),
            self.proj_c(features[2]),
        ]


# ======================================================================== #
#  Loss functions                                                           #
# ======================================================================== #


def distillation_loss(
    encoder_features: list[torch.Tensor],
    decoder_features: list[torch.Tensor],
) -> torch.Tensor:
    """Cosine similarity distillation loss.

    Measures how well the decoder reconstructs encoder features.
    Low loss → good reconstruction (normal),
    High loss → failed reconstruction (anomalous).
    """
    cos = nn.CosineSimilarity(dim=1)
    loss = torch.tensor(0.0, device=encoder_features[0].device)
    for enc, dec in zip(encoder_features, decoder_features):
        loss = loss + torch.mean(
            1 - cos(enc.view(enc.shape[0], -1), dec.view(dec.shape[0], -1))
        )
    return loss


class CosineReconstruct(nn.Module):
    """Cosine reconstruction loss between projected feature maps."""

    def forward(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        return torch.mean(
            1
            - F.cosine_similarity(
                x.view(x.shape[0], -1),
                y.view(y.shape[0], -1),
            )
        )


class Revisit_RDLoss(nn.Module):
    """Multi-task projection loss for RD++ (CVPR 2023, Tran Dinh Tien et al.).

    Three components:
      1. **SSOT** — Self-Supervised Optimal Transport via Sinkhorn distance.
         Encourages compact, transferable normal-class representations.
      2. **Reconstruct** — Cosine similarity between projected noisy and
         projected normal features.
      3. **Contrast** — Cosine embedding loss to push encoder-noise features
         away from projected-normal features.

    Final:  (L_ssot + 0.01 × L_reconstruct + 0.1 × L_contrast) / 1.11
    """

    def __init__(self) -> None:
        super().__init__()
        if HAS_GEOMLOSS:
            self.sinkhorn = geomloss.SamplesLoss(
                loss="sinkhorn",
                p=2,
                blur=0.05,
                reach=None,
                diameter=10_000_000,
                scaling=0.95,
                truncate=10,
                debias=True,
                potentials=False,
                verbose=False,
                backend="auto",
            )
        else:
            self.sinkhorn = None

        self.reconstruct = CosineReconstruct()
        self.contrast = nn.CosineEmbeddingLoss(margin=0.5)

    def _sinkhorn_distance(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        if self.sinkhorn is not None:
            return self.sinkhorn(
                torch.softmax(x.view(x.shape[0], -1), -1),
                torch.softmax(y.view(y.shape[0], -1), -1),
            )
        # Fallback: simple MMD if geomloss is not installed
        x_flat = x.view(x.shape[0], -1)
        y_flat = y.view(y.shape[0], -1)
        return torch.mean((x_flat.mean(0) - y_flat.mean(0)) ** 2)

    def forward(
        self,
        noised_features: list[torch.Tensor],
        projected_noised: list[torch.Tensor],
        projected_normal: list[torch.Tensor],
    ) -> torch.Tensor:
        batch_size = projected_normal[0].shape[0]
        device = projected_normal[0].device
        target = -torch.ones(batch_size, device=device)

        shuffle_idx = torch.randperm(batch_size, device=device)
        shuffled = [pn[shuffle_idx] for pn in projected_normal]

        loss_ssot = sum(
            self._sinkhorn_distance(pn, sh)
            for pn, sh in zip(projected_normal, shuffled)
        )
        loss_reconstruct = sum(
            self.reconstruct(pn, pp)
            for pn, pp in zip(projected_noised, projected_normal)
        )
        loss_contrast = sum(
            self.contrast(
                nf.view(nf.shape[0], -1),
                pn.view(pn.shape[0], -1),
                target,
            )
            for nf, pn in zip(noised_features, projected_normal)
        )
        return (loss_ssot + 0.01 * loss_reconstruct + 0.1 * loss_contrast) / 1.11


# ======================================================================== #
#  Dataset with pseudo-anomaly noise                                        #
# ======================================================================== #


class ImageFolderSimple(Dataset):
    """Load images from a flat directory (no labels)."""

    def __init__(
        self, root: str | Path, transform: transforms.Compose | None = None
    ) -> None:
        self.paths: list[Path] = sorted(
            p
            for p in Path(root).iterdir()
            if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
        )
        self.transform = transform

    def __len__(self) -> int:
        return len(self.paths)

    def __getitem__(self, idx: int) -> torch.Tensor:
        img = Image.open(self.paths[idx]).convert("RGB")
        if self.transform is not None:
            img = self.transform(img)
        return img


class TrainingDataset(Dataset):
    """Training dataset returning (normal_image, noisy_image) pairs.

    Generates pseudo-anomalies by injecting structured noise
    (multi-octave Gaussian-filtered random noise approximating simplex noise)
    into a random rectangular patch of each training image.

    Noise generation strategy:
      1. Pick a random rectangular region (10–size//8 pixels per side).
      2. Generate 6-octave spatially-correlated noise via Gaussian filtering.
      3. Add to the image at 20 % amplitude.
      This closely approximates the original RD++ simplex noise approach
      without requiring the numba dependency.
    """

    def __init__(
        self,
        root: str | Path,
        image_size: int = 256,
        geometric_transform=None,
    ) -> None:
        self.paths: list[Path] = sorted(
            p
            for p in Path(root).iterdir()
            if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
        )
        self.image_size = image_size
        self.geometric_transform = geometric_transform
        self.normalize = transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD)

    def __len__(self) -> int:
        return len(self.paths)

    def _generate_noise_patch(self, size: int) -> np.ndarray:
        """Multi-octave Gaussian noise patch (approximates simplex noise)."""
        h_noise = np.random.randint(10, max(11, size // 8))
        w_noise = np.random.randint(10, max(11, size // 8))
        start_h = np.random.randint(1, max(2, size - h_noise))
        start_w = np.random.randint(1, max(2, size - w_noise))

        noise = np.zeros((3, h_noise, w_noise), dtype=np.float32)
        amplitude = 1.0
        for octave in range(6):
            raw = np.random.randn(3, h_noise, w_noise).astype(np.float32)
            sigma = max(0.5, min(h_noise, w_noise) / (4 * (2**octave)))
            for c in range(3):
                raw[c] = scipy_gaussian_filter(raw[c], sigma=sigma)
            noise += amplitude * raw
            amplitude *= 0.6

        nmax = np.abs(noise).max() + 1e-8
        noise = noise / nmax

        mask = np.zeros((3, size, size), dtype=np.float32)
        mask[:, start_h : start_h + h_noise, start_w : start_w + w_noise] = 0.2 * noise
        return mask

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        img = Image.open(self.paths[idx]).convert("RGB")

        if self.geometric_transform is not None:
            # Benchmark mode: apply shared geometric transforms, then to array
            img = self.geometric_transform(img)

        img = (
            img.resize((self.image_size, self.image_size), Image.BILINEAR)
            if self.geometric_transform is None
            else img
        )
        img_np = np.array(img, dtype=np.float32) / 255.0
        img_np = img_np.transpose(2, 0, 1)  # [3, H, W]

        # Normal image
        img_normal = self.normalize(torch.from_numpy(img_np.copy()))

        # Noisy image (pseudo-anomaly)
        noise_mask = self._generate_noise_patch(self.image_size)
        img_noisy = np.clip(img_np + noise_mask, 0.0, 1.0)
        img_noise = self.normalize(torch.from_numpy(img_noisy))

        return img_normal, img_noise


# ======================================================================== #
#  Anomaly map computation (used for validation during training)            #
# ======================================================================== #


def compute_anomaly_map(
    encoder_features: list[torch.Tensor],
    decoder_features: list[torch.Tensor],
    out_size: int,
) -> torch.Tensor:
    """Compute image-level anomaly map from encoder–decoder cosine distance.

    For each scale, 1 − cos_similarity is upsampled to out_size and summed.
    Returns: [B, out_size, out_size] anomaly map (higher = more anomalous).
    """
    B = encoder_features[0].shape[0]
    device = encoder_features[0].device
    anomaly_map = torch.zeros(B, out_size, out_size, device=device)

    for enc, dec in zip(encoder_features, decoder_features):
        a_map = 1 - F.cosine_similarity(enc, dec, dim=1)  # [B, H, W]
        a_map = F.interpolate(
            a_map.unsqueeze(1),
            size=out_size,
            mode="bilinear",
            align_corners=True,
        )
        anomaly_map += a_map.squeeze(1)

    return anomaly_map


# ======================================================================== #
#  Training function                                                        #
# ======================================================================== #


def train_rd_plus_plus(
    split_dir: str,
    output_dir: str,
    image_size: int = 256,
    batch_size: int = 16,
    epochs: int = 200,
    proj_lr: float = 1e-3,
    distill_lr: float = 5e-3,
    weight_proj: float = 0.2,
    accumulation_steps: int = 2,
    patience: int = 30,
    min_train_images: int = 10,
    benchmark_geometric_transform=None,
    benchmark_mode: bool = False,
) -> str:
    """
    Train RD++ on a prepared dataset split.

    Args:
        split_dir:            Path to split (must contain train/good/).
        output_dir:           Where to save model checkpoints.
        image_size:           Resize target (square).
        batch_size:           Batch size for training.
        epochs:               Maximum training epochs.
        proj_lr:              Learning rate for projection layer (Adam).
        distill_lr:           Learning rate for decoder + BN (Adam).
        weight_proj:          Weight for projection loss in total loss.
        accumulation_steps:   Gradient accumulation steps.
        patience:             Early stopping patience (epochs w/o improvement).
        min_train_images:     Minimum OK images required.

    Returns:
        Path to the best model checkpoint (.pth file).
    """
    split_dir = Path(split_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info(f"Training RD++  |  split={split_dir}  device={device}")

    # ------------------------------------------------------------------
    # Guard: minimum training images
    # ------------------------------------------------------------------
    # Support both new (ok/) and legacy (good/) directory names
    train_dir = split_dir / "train" / "ok"
    if not train_dir.is_dir():
        train_dir = split_dir / "train" / "good"
    n_images = sum(
        1
        for p in train_dir.iterdir()
        if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
    )

    if n_images < min_train_images:
        msg = (
            f"\n{'=' * 60}\n"
            f"  TRAINING REJECTED: not enough OK images\n"
            f"  Found:    {n_images} images\n"
            f"  Required: at least {min_train_images}\n"
            f"\n"
            f"  RD++ needs ≥ {min_train_images} OK images for the\n"
            f"  decoder to learn meaningful feature reconstructions.\n"
            f"\n"
            f"  Please collect more OK samples and try again.\n"
            f"{'=' * 60}"
        )
        logger.error(msg)
        raise ValueError(msg)

    logger.info(f"Training images: {n_images}")

    # ------------------------------------------------------------------
    # Step 1: Data
    # ------------------------------------------------------------------
    train_dataset = TrainingDataset(
        train_dir,
        image_size=image_size,
        geometric_transform=benchmark_geometric_transform,
    )
    # In benchmark mode, use num_workers=0 to ensure np.random reproducibility
    # (TrainingDataset uses np.random for pseudo-anomaly generation).
    if benchmark_mode:
        n_workers = 0
        dl_generator = torch.Generator()
        dl_generator.manual_seed(42)  # seeded from set_seed() earlier
    else:
        n_workers = min(4, max(1, len(train_dataset)))
        dl_generator = None
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=n_workers,
        pin_memory=(device.type == "cuda") and n_workers > 0,
        drop_last=(len(train_dataset) > batch_size),
        generator=dl_generator,
    )

    # ------------------------------------------------------------------
    # Step 2: Build models
    # ------------------------------------------------------------------
    encoder = Encoder().to(device)
    encoder.eval()

    bn = BottleneckNetwork().to(device)
    decoder = Decoder().to(device)
    proj_layer = MultiProjectionLayer(base=64).to(device)

    proj_loss_fn = Revisit_RDLoss()

    n_params = (
        sum(p.numel() for p in bn.parameters())
        + sum(p.numel() for p in decoder.parameters())
        + sum(p.numel() for p in proj_layer.parameters())
    )
    logger.info(f"Trainable parameters: {n_params:,}")

    # ------------------------------------------------------------------
    # Step 3: Optimisers (separate for projection and distillation)
    # ------------------------------------------------------------------
    optimizer_proj = torch.optim.Adam(
        proj_layer.parameters(),
        lr=proj_lr,
        betas=(0.5, 0.999),
    )
    optimizer_distill = torch.optim.Adam(
        list(decoder.parameters()) + list(bn.parameters()),
        lr=distill_lr,
        betas=(0.5, 0.999),
    )

    # ------------------------------------------------------------------
    # Step 4: Training loop
    # ------------------------------------------------------------------
    best_loss = float("inf")
    patience_counter = 0
    best_epoch = 0
    best_ckpt_path = output_dir / "model_best.pth"

    logger.info(
        f"Training: max {epochs} epochs, patience={patience}, "
        f"batch={batch_size}, accum={accumulation_steps}, "
        f"proj_lr={proj_lr}, distill_lr={distill_lr}, "
        f"weight_proj={weight_proj}"
    )
    if not HAS_GEOMLOSS:
        logger.warning(
            "geomloss not installed — using MMD fallback for SSOT loss. "
            "Install geomloss for optimal results."
        )

    for epoch in range(1, epochs + 1):
        bn.train()
        decoder.train()
        proj_layer.train()

        epoch_loss_total = 0.0
        epoch_loss_distill = 0.0
        epoch_loss_proj = 0.0
        n_batches = 0

        optimizer_proj.zero_grad()
        optimizer_distill.zero_grad()

        for i, (img, img_noise) in enumerate(train_loader):
            img = img.to(device)
            img_noise = img_noise.to(device)

            # Frozen encoder — no gradients
            with torch.no_grad():
                inputs = encoder(img)
                inputs_noise = encoder(img_noise)

            # Projection (both normal and noisy)
            projected_noise, projected_normal = proj_layer(
                inputs,
                features_noise=inputs_noise,
            )

            # Projection loss (SSOT + reconstruct + contrast)
            L_proj = proj_loss_fn(inputs_noise, projected_noise, projected_normal)

            # Distillation loss (decoder reconstructs encoder features)
            outputs = decoder(bn(projected_normal))
            L_distill = distillation_loss(inputs, outputs)

            loss = L_distill + weight_proj * L_proj
            loss = loss / accumulation_steps
            loss.backward()

            if (i + 1) % accumulation_steps == 0:
                optimizer_proj.step()
                optimizer_distill.step()
                optimizer_proj.zero_grad()
                optimizer_distill.zero_grad()

            epoch_loss_total += L_distill.item() + weight_proj * L_proj.item()
            epoch_loss_distill += L_distill.item()
            epoch_loss_proj += L_proj.item()
            n_batches += 1

        # Flush remaining gradients
        if n_batches % accumulation_steps != 0:
            optimizer_proj.step()
            optimizer_distill.step()
            optimizer_proj.zero_grad()
            optimizer_distill.zero_grad()

        avg_total = epoch_loss_total / max(n_batches, 1)
        avg_distill = epoch_loss_distill / max(n_batches, 1)
        avg_proj = epoch_loss_proj / max(n_batches, 1)

        # ---- Early stopping ----
        min_delta = 1e-4
        if avg_total < best_loss - min_delta:
            best_loss = avg_total
            best_epoch = epoch
            patience_counter = 0
            _save_checkpoint(
                best_ckpt_path,
                decoder,
                bn,
                proj_layer,
                image_size,
            )
        else:
            patience_counter += 1

        # ---- Logging ----
        if epoch % 10 == 0 or epoch == 1 or epoch == epochs:
            logger.info(
                f"  Epoch {epoch:>3}/{epochs}  "
                f"L_total={avg_total:.4f}  L_dist={avg_distill:.4f}  "
                f"L_proj={avg_proj:.4f}  best={best_loss:.4f}  "
                f"patience={patience_counter}/{patience}"
            )

        if patience_counter >= patience:
            logger.info(
                f"  Early stopping at epoch {epoch} "
                f"(best epoch: {best_epoch}, best loss: {best_loss:.4f})"
            )
            break

    logger.info(
        f"Best checkpoint: {best_ckpt_path}  "
        f"(epoch {best_epoch}, loss={best_loss:.4f})"
    )
    return str(best_ckpt_path)


# ======================================================================== #
#  Checkpoint helpers                                                       #
# ======================================================================== #


def _save_checkpoint(
    path: Path,
    decoder: Decoder,
    bn: BottleneckNetwork,
    proj_layer: MultiProjectionLayer,
    image_size: int,
) -> None:
    config = {
        "image_size": image_size,
        "backbone": "wide_resnet50_2",
        "decoder_layers": (3, 4, 6),
        "width_per_group": 128,
        "proj_base": 64,
    }
    torch.save(
        {
            "decoder_state_dict": decoder.state_dict(),
            "bn_state_dict": bn.state_dict(),
            "proj_state_dict": proj_layer.state_dict(),
            "config": config,
        },
        path,
    )


# ======================================================================== #
#  CLI entry point                                                          #
# ======================================================================== #

if __name__ == "__main__":
    import argparse

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )

    parser = argparse.ArgumentParser(
        description="Train RD++ model",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--split-dir", type=str, required=True, help="Path to dataset split directory"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="experiments/train_output",
        help="Path to save model checkpoint and logs",
    )
    parser.add_argument("--image-size", type=int, default=256)
    parser.add_argument(
        "--batch-size", type=int, default=16, help="Batch size for training"
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=200,
        help="Maximum training epochs (early stopping may end sooner)",
    )
    parser.add_argument(
        "--proj-lr",
        type=float,
        default=1e-3,
        help="Projection layer learning rate (Adam)",
    )
    parser.add_argument(
        "--distill-lr",
        type=float,
        default=5e-3,
        help="Decoder + BN learning rate (Adam)",
    )
    parser.add_argument(
        "--weight-proj",
        type=float,
        default=0.2,
        help="Weight for projection loss in total loss",
    )
    parser.add_argument(
        "--accumulation-steps", type=int, default=2, help="Gradient accumulation steps"
    )
    parser.add_argument(
        "--patience",
        type=int,
        default=30,
        help="Early stopping patience (epochs w/o improvement)",
    )
    parser.add_argument(
        "--min-train-images",
        type=int,
        default=10,
        help="Minimum OK images required to start training",
    )

    args = parser.parse_args()

    ckpt = train_rd_plus_plus(
        split_dir=args.split_dir,
        output_dir=args.output_dir,
        image_size=args.image_size,
        batch_size=args.batch_size,
        epochs=args.epochs,
        proj_lr=args.proj_lr,
        distill_lr=args.distill_lr,
        weight_proj=args.weight_proj,
        accumulation_steps=args.accumulation_steps,
        patience=args.patience,
        min_train_images=args.min_train_images,
    )
    print(f"\nModel checkpoint: {ckpt}")
